#!/bin/bash

# Run your tests here. This script shall exit with a non-zero exit status to
# signal that the whole build has failed.

set -e
set -x

if [ -z ${PHANTOMJS_BIN} ]; then
    export PHANTOMJS_BIN=/usr/local/bin/phantomjs
fi

# Go to the root dir.
cd ..
npm test
